### PR TITLE
Add GitHub icon

### PR DESCRIPTION
**Pull request by CompuIves**

### CODE REVIEW

**Comment by SaraVieira** [comment]
The icon is not showing up in the sandbox :(

**Comment by CompuIves** [comment]
Hmmm, for me it is: 
image

**Comment by SaraVieira** [comment]
But only in one of the sets, is that the intention?

**Comment by CompuIves** [comment]
Yeah hmm, I only put the color one in since that's the only one I needed 😅 .

**Comment by SaraVieira** [comment]
Makes sense, merge away

I can't merge ahah

**Pull request merged**
